package org.example.declarativeagenda;

import org.example.declarativeagenda.SampleData;
import org.kie.api.runtime.rule.Match;

rule "Rule_A" @Eager @phase("Phase_1")
    lock-on-active true

    when
        $data : SampleData()
    then
        $data.addRuleName("Rule_A");
        modify ($data) { setLatestRule("Rule_A") };
        System.out.println($data);
end

rule "Rule_B" @Eager @phase("Phase_2")
    lock-on-active true
    
    when
        $data : SampleData()
    then
        $data.addRuleName("Rule_B");
        modify ($data) { setLatestRule("Rule_B") };
        System.out.println($data);
end

rule "Rule_C" @Eager @phase("Phase_3")
    lock-on-active true

    when
        $data : SampleData()
    then
        $data.addRuleName("Rule_C");
        modify ($data) { setLatestRule("Rule_C") };
        System.out.println($data);
end

rule "BlockPhaseTwoRule" @Direct @Eager

    when
        $m: Match(rule.metaData["phase"] == "Phase_2")
        $d: SampleData(latestRule == "Rule_A")
    then
        System.out.println("ブロック");
        kcontext.blockMatch($m);
end

rule "UnblockPhaseTwoRule" @Direct @Eager

    when
        $m: Match(rule.metaData["phase"] == "Phase_2")
        $d: SampleData(latestRule == "Rule_C")
    then
        System.out.println("ブロック解除");
        kcontext.unblockAllMatches($m);
end
