package org.example.azure.negaposirule.ruleunit;
unit PriorityRuleUnit;


rule "長期顧客_ネガティブ"
    when
        /customer[ contractPeriod >= 2 ];
        /analyzedReviewComment[ sentiment().equals("negative") ];
    then
        priority.set(new Priority(5));
end


rule "長期顧客_ニュートラル"
    when
        /customer[ contractPeriod >= 2 ];
        /analyzedReviewComment[ sentiment().equals("neutral") ];
    then
        priority.set(new Priority(2));
end

rule "長期顧客_ポジティブ"
    when
        /customer[ contractPeriod >= 2 ];
        /analyzedReviewComment[ sentiment().equals("positive") ];
    then
        priority.set(new Priority(3));
end

rule "短期顧客_ネガティブ"
    when
        /customer[ contractPeriod < 2 ];
        /analyzedReviewComment[ sentiment().equals("negative") ];
    then
        priority.set(new Priority(3));
end

rule "短期顧客_ニュートラル"
    when
        /customer[ contractPeriod < 2 ];
        /analyzedReviewComment[ sentiment().equals("neutral") ];
    then
        priority.set(new Priority(1));
end

rule "短期顧客_ポジティブ"
    when
        /customer[ contractPeriod < 2 ];
        /analyzedReviewComment[ sentiment().equals("positive") ];
    then
        priority.set(new Priority(2));
end

query FindPriority
    $p: /priority
end
