import org.example.Person
import org.example.Drink

// こちらの定義ではコンパイルはとおる

query query_ok(String $age1, String $age2, String $age3, String $age4, String $age5, String $age6, String $age7, String $age8, String $age9, String $age10)
    // 10個の引数をもつ
end


// こちらの定義ではコンパイルエラーとなる

// query query_ng(String $age1, String $age2, String $age3, String $age4, String $age5, String $age6, String $age7, String $age8, String $age9, String $age10, String $age11)
    // 11個の引数をもつ
// end


rule "Child"
    when
        $person : Person( age != 20)
        $drink : Drink()
    then
        $drink.setName( "Orange Juice" );
end
