package org.example.integratewithopenai.unstructuredinput.ruleunit;
unit PriorityRuleUnit;


rule "Any"
    when
        /customer[ contractPeriod < 10 ];
        /inquiryCategory[ value.equals("A") ];
    then
        priority.set(new Priority(2));
end


rule "Hello"
    when
        /customer[ contractPeriod < 10 ];
        /inquiryCategory[ value.equals("B") ];
    then
        System.out.println("Hello");
end


query FindPriority
    $p: /priority
end
