plugins {
    id 'java'
}

group = 'org.example.ruleunit.drlsample'
version = '1.0.0-SNAPSHOT'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

def droolsVersion = '10.2.0'

dependencies {
    // Drools
    implementation "org.drools:drools-mvel:${droolsVersion}"
    implementation "org.drools:drools-xml-support:${droolsVersion}"
    implementation "org.drools:drools-ruleunits-engine:${droolsVersion}"

    // Logging
    implementation 'org.slf4j:slf4j-simple:2.0.13'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.0'
}

test {
    useJUnitPlatform()

    testLogging.showStandardStreams = true
}